name: Terraform Destroy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.11.2'
          terraform_wrapper: false

      - name: Terraform Initialize
        run: |
          terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-destroy

      - name: Terraform Destroy
        run: |
          terraform workspace select $ENVIRONMENT
          terraform apply -auto-approve tfplan-destroy