name: Terraform Plan Destroy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  terraform-plan-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.11.2'
          terraform_wrapper: false

      - name: Terraform Initialize
        run: |
          terraform init

      - name: Terraform Plan Destroy
        id: plan-destroy
        env:
          TF_VAR_google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
          TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TF_VAR_mongodb_url: ${{ secrets.MONGODB_URL }}
          TF_VAR_database_name: ${{ secrets.DATABASE_NAME }}
          TF_VAR_opensubtitles_api_key: ${{ secrets.OPENSUBTITLES_API_KEY }}
          TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
          TF_VAR_backend_image_tag: ${{ env.TF_VAR_backend_image_tag }}
          TF_VAR_nextauth_url: ${{ secrets.NEXTAUTH_URL }}
          TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
        run: |
          terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT
          terraform plan -destroy \
            -var="name_prefix=english" \
            -var="environment=$ENVIRONMENT" \
            -var-file="environments/$ENVIRONMENT/terraform.tfvars" \
            -out=tfplan-destroy

      - name: Upload Terraform Plan Destroy
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-destroy
          path: tfplan-destroy
          retention-days: 1